blueprint:
  name: Day/Night Sensor Controlled Lighting
  description: >-
    Automatically toggles between day and night lighting based on a binary sensor and specified time intervals. V1
  domain: automation

  input:
    day_light:
      name: Daytime Light
      description: "The main (bright) light entity to switch on during daytime."
      selector:
        entity:
          domain:
            - light
            - switch

    night_light:
      name: Nighttime Light
      description: "The softer (night) light entity to switch on during nighttime."
      selector:
        entity:
          domain:
            - light
            - switch

    binary_sensor:
      name: Motion/Presence Sensor
      description: "The binary sensor that triggers the lighting."
      selector:
        entity:
          domain: binary_sensor

    day_start:
      name: Daytime Start
      description: "Time when daytime lighting starts."
      selector:
        time:

    night_start:
      name: Nighttime Start
      description: "Time when nighttime lighting starts."
      selector:
        time:

trigger:
  - platform: state
    entity_id: !input binary_sensor

variables:
  day_start: !input day_start
  night_start: !input night_start

condition: []

action:
  - choose:
      - conditions:
          - condition: time
            after: !input day_start
            before: !input night_start
          - condition: state
            entity_id: !input binary_sensor
            state: 'on'
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input day_light

      - conditions:
          - condition: time
            after: !input night_start
            before: !input day_start
          - condition: state
            entity_id: !input binary_sensor
            state: 'on'
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input night_light

      - conditions:
          - condition: state
            entity_id: !input binary_sensor
            state: 'off'
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id:
                - !input day_light
                - !input night_light
