blueprint:
  name: Keller Aquarium Controller
  description: Ein Blueprint um das Keller Aquarium zu automatisieren.
  domain: automation
  input:
    temperature_sensor:
      name: Temperatursensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    target_switch:
      name: Zu steuernder Schalter
      selector:
        entity:
          domain: switch
    lower_temp:
      name: Untere Temperaturschwelle
      description: Schalter wird eingeschaltet, wenn die Temperatur auf oder unter diesen Wert f채llt
      default: 20.0
      selector:
        number:
          min: 15
          max: 35
          step: 0.1
          unit_of_measurement: 째C
    upper_temp:
      name: Obere Temperaturschwelle
      description: Schalter wird ausgeschaltet, wenn die Temperatur auf oder 체ber diesen Wert steigt
      default: 22.0
      selector:
        number:
          min: 15
          max: 35
          step: 0.1
          unit_of_measurement: 째C

trigger:
  - platform: numeric_state
    entity_id: !input temperature_sensor
    below: !input lower_temp
  - platform: numeric_state
    entity_id: !input temperature_sensor
    above: !input upper_temp

condition: []

action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input temperature_sensor
            below: !input lower_temp
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input target_switch
      - conditions:
          - condition: numeric_state
            entity_id: !input temperature_sensor
            above: !input upper_temp
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input target_switch