blueprint:
  name: Awetrix Notification Timer
  description: |
    A blueprint to send notifications to Awetrix 3.0 API with a calculated percentage
    based on the elapsed time, triggered by another automation. Allows configuration
    of total time, time interval between messages, and the Awetrix 3.0 API IP.
  domain: automation
  input:
    awetrix_ip:
      name: Awetrix 3.0 IP Address
      description: The IP address of the Awetrix 3.0 API.
      selector:
        text:
    total_time:
      name: Total Time
      description: The total time (in minutes) over which the percentage is calculated.
      selector:
        number:
          min: 1
          max: 1440
          step: 1
          unit_of_measurement: minutes
    interval:
      name: Notification Interval
      description: Time between notifications sent to Awetrix (in minutes).
      selector:
        number:
          min: 1
          max: 60
          step: 1
          unit_of_measurement: minutes

trigger:
  - platform: event
    event_type: automation_trigger
    event_data:
      blueprint: "Awetrix Notification Timer"

variables:
  awetrix_ip: !input awetrix_ip
  total_time: !input total_time
  interval: !input interval

action:
  - alias: "Send notifications to Awetrix API"
    repeat:
      sequence:
        - service: rest_command.awetrix_notification
          data:
            message: "{{ (repeat.index0 / (total_time * 60 / (interval * 60)) * 100) | round(2) }}%"
        - delay:
            minutes: "{{ interval }}"
      until:
        condition: template
        value_template: "{{ repeat.index0 * interval * 60 >= total_time * 60 }}"

rest_command:
  awetrix_notification:
    url: "http://{{ awetrix_ip }}/api"
    method: POST
    headers:
      Content-Type: "application/json"
    payload: '{"text": "{{ message }}"}'

mode: single
